CONNECT SYSTEM as SYSDBA;

DROP USER DBSEC_ADMIN CASCADE;

CREATE USER DBSEC_ADMIN IDENTIFIED BY tec5363admin
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA  30M ON USERS;
SELECT USERNAME,PASSWORD,DEFAULT_TABLESPACE,TEMPORARY_TABLESPACE FROM DBA_USERS WHERE USERNAME='DBSEC_ADMIN';


DROP USER DBSEC_CLERK CASCADE;

CREATE USER DBSEC_CLERK IDENTIFIED BY tec5363clerk
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA  30M ON USERS;
SELECT USERNAME,PASSWORD,DEFAULT_TABLESPACE,TEMPORARY_TABLESPACE FROM DBA_USERS WHERE USERNAME='DBSEC_CLERK';


DROP USER DBSEC_DEV CASCADE;

CREATE USER DBSEC_DEV IDENTIFIED BY tec5363$dev
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA  30M ON USERS;
SELECT USERNAME,PASSWORD,DEFAULT_TABLESPACE,TEMPORARY_TABLESPACE FROM DBA_USERS WHERE USERNAME='DBSEC_DEV';

DROP PROFILE DBSEC_ADMIN_PROF CASCADE;

CREATE PROFILE  DBSEC_ADMIN_PROF
LIMIT
SESSIONS_PER_USER 5
CONNECT_TIME 480
IDLE_TIME 60
PASSWORD_LIFE_TIME 30
PASSWORD_GRACE_TIME 7;

DROP PROFILE DBSEC_CLERK_PROF CASCADE;

CREATE PROFILE  DBSEC_CLERK_PROF
LIMIT
SESSIONS_PER_USER 1
CPU_PER_CALL 5
CONNECT_TIME 480
IDLE_TIME 30
LOGICAL_READS_PER_CALL 10
FAILED_LOGIN_ATTEMPTS 3
PASSWORD_LIFE_TIME 30
PASSWORD_LOCK_TIME 3
PASSWORD_GRACE_TIME 14;

DROP PROFILE DBSEC_DEV_PROF CASCADE;

CREATE PROFILE  DBSEC_DEV_PROF
LIMIT
CONNECT_TIME 120
IDLE_TIME 120
CPU_PER_CALL 6000
PASSWORD_LIFE_TIME 30
PASSWORD_GRACE_TIME 14;

DROP ROLE DBSEC_ADMIN_ROLE CASCADE;

CREATE ROLE DBSEC_ADMIN_ROLE;

GRANT SELECT, ALTER ON DBSEC.SUPPLIER TO DBSEC_ADMIN_ROLE;
GRANT SELECT, ALTER ON DBSEC.SHIPMENT_METHOD TO DBSEC_ADMIN_ROLE;
GRANT SELECT, ALTER ON DBSEC.DEPARTMENT TO DBSEC_ADMIN_ROLE;
GRANT SELECT, ALTER ON DBSEC.JOB TO DBSEC_ADMIN_ROLE;
GRANT SELECT, ALTER ON DBSEC.EMPLOYEE TO DBSEC_ADMIN_ROLE;
GRANT SELECT, ALTER ON DBSEC.SALES_COMMISSION TO DBSEC_ADMIN_ROLE;
GRANT SELECT, ALTER ON DBSEC.PROMOTION TO DBSEC_ADMIN_ROLE;
GRANT SELECT, ALTER ON DBSEC.CATEGORY TO DBSEC_ADMIN_ROLE;
GRANT SELECT, ALTER ON DBSEC.PRODUCT TO DBSEC_ADMIN_ROLE;
GRANT SELECT, ALTER ON DBSEC.PRODUCT_SUPPLIER TO DBSEC_ADMIN_ROLE;
GRANT SELECT, ALTER ON DBSEC.PRODUCT_PRICE TO DBSEC_ADMIN_ROLE;
GRANT SELECT, ALTER ON DBSEC.PRODUCT_INVENTORY TO DBSEC_ADMIN_ROLE;
GRANT SELECT, ALTER ON DBSEC.PAYMENT_METHOD TO DBSEC_ADMIN_ROLE;
GRANT SELECT, ALTER ON DBSEC.CUSTOMER TO DBSEC_ADMIN_ROLE;
GRANT SELECT, ALTER ON DBSEC.ORDER_TAB TO DBSEC_ADMIN_ROLE;
GRANT SELECT, ALTER ON DBSEC.ORDER_LINE TO DBSEC_ADMIN_ROLE;
GRANT SELECT, ALTER ON DBSEC.EMPLOYEE_RANK TO DBSEC_ADMIN_ROLE;

DROP ROLE DBSEC_CLERK_ROLE CASCADE;

CREATE ROLE DBSEC_CLERK_ROLE;

GRANT SELECT, INSERT, UPDATE ON DBSEC.SUPPLIER TO DBSEC_CLERK_ROLE;
GRANT SELECT, INSERT, UPDATE ON DBSEC.SHIPMENT_METHOD TO DBSEC_CLERK_ROLE;
GRANT SELECT,INSERT, UPDATE  ON DBSEC.DEPARTMENT TO DBSEC_CLERK_ROLE;
GRANT SELECT, INSERT, UPDATE ON DBSEC.JOB TO DBSEC_CLERK_ROLE;
GRANT SELECT, INSERT, UPDATE ON DBSEC.EMPLOYEE TO DBSEC_CLERK_ROLE;
GRANT SELECT, INSERT, UPDATE ON DBSEC.SALES_COMMISSION TO DBSEC_CLERK_ROLE;
GRANT SELECT, INSERT, UPDATE ON DBSEC.PROMOTION TO DBSEC_CLERK_ROLE;
GRANT SELECT, INSERT, UPDATE ON DBSEC.CATEGORY TO DBSEC_CLERK_ROLE;
GRANT SELECT, INSERT, UPDATE ON DBSEC.PRODUCT TO DBSEC_CLERK_ROLE;
GRANT SELECT, INSERT, UPDATE ON DBSEC.PRODUCT_SUPPLIER TO DBSEC_CLERK_ROLE;
GRANT SELECT, INSERT, UPDATE ON DBSEC.PRODUCT_PRICE TO DBSEC_CLERK_ROLE;
GRANT SELECT, INSERT, UPDATE ON DBSEC.PRODUCT_INVENTORY TO DBSEC_CLERK_ROLE;
GRANT SELECT,INSERT, UPDATE ON DBSEC.PAYMENT_METHOD TO DBSEC_CLERK_ROLE;
GRANT SELECT, INSERT, UPDATE ON DBSEC.CUSTOMER TO DBSEC_CLERK_ROLE;
GRANT SELECT, INSERT, UPDATE ON DBSEC.ORDER_TAB TO DBSEC_CLERK_ROLE;
GRANT SELECT, INSERT, UPDATE ON DBSEC.ORDER_LINE TO DBSEC_CLERK_ROLE;
GRANT SELECT, INSERT, UPDATE ON DBSEC.EMPLOYEE_RANK TO DBSEC_CLERK_ROLE;

DROP ROLE DBSEC_SUPERVISOR_ROLE CASCADE;

CREATE ROLE DBSEC_SUPERVISOR_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON DBSEC.SUPPLIER TO DBSEC_SUPERVISOR_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON DBSEC.SHIPMENT_METHOD TO DBSEC_SUPERVISOR_ROLE;
GRANT SELECT,INSERT, UPDATE, DELETE  ON DBSEC.DEPARTMENT TO DBSEC_SUPERVISOR_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON DBSEC.JOB TO DBSEC_SUPERVISOR_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON DBSEC.EMPLOYEE TO DBSEC_SUPERVISOR_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON DBSEC.SALES_COMMISSION TO DBSEC_SUPERVISOR_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON DBSEC.PROMOTION TO DBSEC_SUPERVISOR_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON DBSEC.CATEGORY TO DBSEC_SUPERVISOR_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON DBSEC.PRODUCT TO DBSEC_SUPERVISOR_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON DBSEC.PRODUCT_SUPPLIER TO DBSEC_SUPERVISOR_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON DBSEC.PRODUCT_PRICE TO DBSEC_SUPERVISOR_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON DBSEC.PRODUCT_INVENTORY TO DBSEC_SUPERVISOR_ROLE;
GRANT SELECT,INSERT, UPDATE, DELETE ON DBSEC.PAYMENT_METHOD TO DBSEC_SUPERVISOR_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON DBSEC.CUSTOMER TO DBSEC_SUPERVISOR_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON DBSEC.ORDER_TAB TO DBSEC_SUPERVISOR_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON DBSEC.ORDER_LINE TO DBSEC_SUPERVISOR_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON DBSEC.EMPLOYEE_RANK TO DBSEC_SUPERVISOR_ROLE;

DROP ROLE DBSEC_QUERY_ROLE CASCADE;

CREATE ROLE DBSEC_QUERY_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON DBSEC.CUSTOMER TO DBSEC_QUERY_ROLE;


GRANT DBSEC_ADMIN_ROLE TO DBSEC_ADMIN;
ALTER USER DBSEC_ADMIN PROFILE DBSEC_ADMIN_PROF;

GRANT DBSEC_CLERK_ROLE TO DBSEC_CLERK;
ALTER USER DBSEC_CLERK PROFILE DBSEC_CLERK_PROF;

GRANT DBSEC_ADMIN_ROLE, DBSEC_SUPERVISOR_ROLE TO DBSEC_DEV;
ALTER USER DBSEC_DEV PROFILE DBSEC_DEV_PROF;

GRANT CREATE SESSION TO DBSEC_CLERK;
CONNECT DBSEC_CLERK/tec5363clerk;

SELECT PRODUCT_ID FROM DBSEC.PRODUCT;