CONNECT SYSTEM;

Define Password='dinesh'
Connect system/&password;

EXEC DBMS_FGA.DROP_POLICY (OBJECT_SCHEMA	=> 'DBSEC', -
			    OBJECT_NAME	=> 'CUSTOMER', -
			    POLICY_NAME	=> 'AUDIT_POLICY_1_SELECT');

EXEC DBMS_FGA.DROP_POLICY (OBJECT_SCHEMA 	=> 'DBSEC', -
			    OBJECT_NAME	=> 'CUSTOMER', -
			    POLICY_NAME	=> 'AUDIT_POLICY_2_CREDIT');

EXEC DBMS_FGA.DROP_POLICY (OBJECT_SCHEMA 	=> 'DBSEC', -
			    OBJECT_NAME	=> 'CUSTOMER', -
			    POLICY_NAME	=> 'AUDIT_POLICY_3_DELETE');

EXEC DBMS_FGA.ADD_POLICY (OBJECT_SCHEMA	=> 'DBSEC', -
			 OBJECT_NAME	=>'CUSTOMER', -
			 POLICY_NAME	=>'AUDIT_POLICY_1_SELECT', -
			 AUDIT_CONDITION	=>NULL, -
			 AUDIT_COLUMN	=>NULL, -
			 HANDLER_SCHEMA	=>NULL, -
			 HANDLER_MODULE	=>NULL, -
			 ENABLE		=>TRUE, -
			 STATEMENT_TYPES	=>'SELECT');

EXEC DBMS_FGA.ADD_POLICY (OBJECT_SCHEMA	=>'DBSEC', -
			 OBJECT_NAME	=> 'CUSTOMER', -
			 POLICY_NAME	=> 'AUDIT_POLICY_2_CREDIT', -
			 AUDIT_CONDITION	=> 'CREDIT_LIMIT >5000', -
			 AUDIT_COLUMN	=> NULL, -
			 HANDLER_SCHEMA	=> NULL, -
			 HANDLER_MODULE	=> NULL, -
			 ENABLE		=> TRUE, -
			 STATEMENT_TYPES	=> 'INSERT, UPDATE');

EXEC DBMS_FGA.ADD_POLICY (OBJECT_SCHEMA	=> 'DBSEC', -
			 OBJECT_NAME	=> 'CUSTOMER', -
			 POLICY_NAME	=> 'AUDIT_POLICY_3_DELETE', -
			 AUDIT_CONDITION	=> NULL, -
			 AUDIT_COLUMN	=> NULL, -
			 HANDLER_SCHEMA	=> NULL, -
			 HANDLER_MODULE	=> NULL, -
			 ENABLE		=> TRUE, -
			 STATEMENT_TYPES	=> 'DELETE');

CONNECT SYS AS SYSDBA;

AUDIT SELECT, INSERT, UPDATE, DELETE ON SYS.AUD$ BY ACCESS;

CONNECT DBSEC/secc$1new;

SELECT CUSTOMER_ID, FIRST_NAME, LAST_NAME, CREDIT_LIMIT FROM CUSTOMER WHERE CUSTOMER_ID=201340;

UPDATE CUSTOMER SET CREDIT_LIMIT=2500000 WHERE CUSTOMER_ID=201340;

DELETE FROM CUSTOMER WHERE CUSTOMER_ID=201340;

COMMIT;
SELECT DB_USER, OBJECT_NAME, POLICY_NAME, SQL_TEXT, TIMESTAMP, STATEMENT_TYPE FROM DBA_FGA_AUDIT_TRAIL;
ROLLBACK;